name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "kartew-bucket-for-lab-php"
  EB_APPLICATION_NAME: "PHP-4-LAB"
  EB_ENVIRONMENT_NAME: "PHP-4-LAB-env"
  DEPLOY_PACKAGE_NAME: "php_app_${{ github.sha }}.zip"
  AWS_REGION_NAME:  "us-east-1"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
     runs-on: ubuntu-latest
     
     steps:
       - name: Git clone our repo
         uses: actions/checkout@v1
         
       - name: Create ZIP deployment package
         run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
         
